### ISSUE TITLE
FTL VSCode extension

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#1152]
- [x] Create extension and lsp client in `ts` (https://github.com/TBD54566975/ftl-vscode)
- [x] Only start `ftl dev` if we're in an FTL project
- [x] Add FTL server output to bottom panel

Future enhancements to be worked on later after initial LSP work is out.
- [ ] Add side panel for FTL extension (could have buttons to restart the server)
- [ ] Add webview for showing FTL events (maybe graph too)?

**Comment by alecthomas** [comment]
Oooh is this published somewhere?!

**Comment by wesbillman** [comment]
Not published yet, but will do! https://github.com/TBD54566975/ftl-vscode/issues/5

In the meantime, I'll update the README.md on that other repo (I wonder if we want the extension in our `ftl` repo at some point 🤔)
