### ISSUE TITLE
Testing module improvements

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1394]
- [x] https://github.com/TBD54566975/ftl/issues/1309
- [x] https://github.com/TBD54566975/ftl/issues/1370
- [x] https://github.com/TBD54566975/ftl/issues/1383
- [x] https://github.com/TBD54566975/ftl/issues/1390
- [x] https://github.com/TBD54566975/ftl/issues/1391
- [x] https://github.com/TBD54566975/ftl/issues/1392
- [x] https://github.com/TBD54566975/ftl/issues/1398

PRs without issues:
- [x] https://github.com/TBD54566975/ftl/pull/1360
- [x] https://github.com/TBD54566975/ftl/pull/1317
- [x] https://github.com/TBD54566975/ftl/pull/1373
