### ISSUE TITLE
Retries

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1528]
Doc: https://hackmd.io/Cbvh60deTPiW6p8B9op9JQ

- [x] https://github.com/TBD54566975/ftl/pull/1552
- [x] https://github.com/TBD54566975/ftl/pull/1554
- [x] https://github.com/TBD54566975/ftl/pull/1583
