### ISSUE TITLE
Fix secrets: 1Password slowness, human meddling, checks

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1951]
Plan:
- [x] https://github.com/TBD54566975/ftl/issues/1946
- [x] https://github.com/TBD54566975/ftl/issues/1889
- [x] https://github.com/TBD54566975/ftl/issues/1947
    - ✅ On hold to batch together breaking changes
- [x] https://github.com/TBD54566975/ftl/issues/1948
- [x] https://github.com/TBD54566975/ftl/issues/1949
- [ ] https://github.com/TBD54566975/ftl/issues/1906

**Comment by matt2e** [comment]
Closing the epic as the next task is slightly independant
