### ISSUE TITLE
Console libraries to review

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2272]
- [x] [Storybook](https://storybook.js.org/)
- [ ] [Tanstack Table](https://tanstack.com/table/latest)
- [x] [Tanstack Store](https://tanstack.com/store/latest)
- [x] #2403
- [ ] Editor stuff (rust has a nice one https://play.rust-lang.org/)
- [ ] Charts https://echarts.apache.org/examples/en/editor.html?c=graph&lang=ts

**Comment by wesbillman** [comment]
All of these have been migrated to the [DX Roadmap](https://github.com/TBD54566975/ftl/issues/2436) issue.
