### ISSUE TITLE
Investigate JVM Runtime Support

### ISSUE THREAD

**Issue by stuartwdouglas** [TBD54566975/ftl#2277]
This is an epic to track work on JVM support. 

- [x] Add support for exposing verbs
- [x] Add support for HTTP ingress
- [x] Add support for cron
- [x] Add support for calling verbs
- [x] Initial test suite support
- [x] Code gen for external modules
- [ ] Instant hot reload support

**Comment by stuartwdouglas** [comment]
I am closing this as the initial implementation is done, the follow up will be tracked under other tickets.
