### ISSUE TITLE
Codebase Health Roadmap

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#2443]
## Backlog

* [ ] How to test against a Kubernetes environment  https://github.com/TBD54566975/ftl/labels/p2
* [ ] Full featured exemplar in FTL repo running on “smoke test” clusters  https://github.com/TBD54566975/ftl/labels/p1
* [ ] FTL having its own dev, staging, prod, and load testing environments https://github.com/TBD54566975/ftl/labels/p1
