### ISSUE TITLE
Mini Design: How do we integrate metrics and tracing from OTEL into the FTL console

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#37]
## Overview

After quite a lot of investigation, we've decided that the best course of action is to leverage OTEL for tracing and metrics rather than rolling our own. We will do this by implementing a custom OTEL exporter in each supported language. Details below.

The rationale here is that the OTEL ecosystem includes instrumentation libraries for everything under the sun: databases, HTTP clients, servers, gRPC, etc. etc. Additionally, end users of FTL can leverage the OTEL SDK in their language and get all of its functionality for "free", as well as exporters for existing observability providers (eg. Datadog, Sentry, etc.). If we rolled our own, while it could be simpler in some ways in that it would just do what we want, we would have to write all of the instrumentation integration code ourselves. That would be a massive amount of work.

## Implementation

As mentioned above, each supported FTL language will need to implement OTEL exporters for metrics and tracing.  The exporters in the deployed code will push via gRPC to the Runner managing the deployment. The Runner will then filter the metrics and spans down to exactly what FTL requires for its internal domain model, before pushing the data to the ControlPlane, again via gRPC. The ControlPlane will then insert the data into its datastore (currently PG).

For traces, we will add attributes identifying traces as being for a particular module/verb, for some FTL specific metrics we'll do the same. It's TBD how we will add attributes to instrumentation outside our control, such as database metrics, etc.

Tasks:
- [x] Delete our custom exporters
- [x] Replace them with the default gRPC exporters eg. [metrics](https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/otlpmetricgrpc/client.go) - will need to be configured to not use TLS (ie. `WithInsecure()`)
- [x] Replace our ObservabilityService with..
- [x] Implement the OTEL [MetricsService](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/collector/metrics/v1/metrics_service.proto#LL30C9-L30C23) using Connect
- [x] #57 
- [x] #58 
- [x] #59 
- [x] #61

**Comment by wesbillman** [comment]
@alecthomas I think we can probably close this one now that we have the `calls` setup. Whatcha think?
