### ISSUE TITLE
Decrease logging noise during development

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#869]
Ideas:

- [x] Go through and adjust log levels for things so they don't log everything FTL is doing (#877(
- [x] Replace goreman with some `ftl dev <>` that does everything. Nice in general, but also so we get coloured logs.
- [x] Buffer logs and if there's an error dump the last N lines of log (#877)
- [x] Maybe make `ftl deploy` also leverage `--exit-after-deploy`?
- [x] Exponential backoff per module
- [x] Does the 5 second delay get canceled if there's a file system change?
- [x] Somehow (?) send `error: Unary RPC failed: unavailable: dial tcp 127.0.0.1:8892: connect: connection refused: /xyz.block.ftl.v1.ControllerService/GetSchema` to debug when starting up? Maybe we don't log errors on initial connection establishment before a timeout?
- [x] Don't log `warn:controller0: Failed to increase deployment replicas: failed to claim runners for oidcauth-86ae51d623: no idle runners found matching labels {"languages":["go"]}: not found` (#890)

**Comment by wesbillman** [comment]
This is complete or has other issues created for it. Closing for now.
