### ISSUE TITLE
CLI UX improvements and build system revamp

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#960]
- [x] #963
- [x] #985
- [x] #979
- [x] #962
- [x] `ftl deploy` will recursively build and deploy all modules in the provided paths, by default it will block until either a timeout error occurs or all modules are deployed and live. #1002 
- [x] #961
- [x] #969
- [x] #970
- [x] #967
- [x] #966
- [x] #973
- [x] (2) Another system for repeatedly building in parallel until everything reconciles.
- [x] #1027
- [x] One of these systems needs to understand schema dependencies and which modules to rebuild when modules change.
- [x] We will need a bounded work queue to avoid killing the users computer.
- [x] We'll want a flag to control concurrency.
- [x] [Ideally each build system can feedback how concurrent it is. eg. if each Go build uses 10 cores, we don't want to build 10 Go modules at once.](https://github.com/TBD54566975/ftl/blob/main/buildengine/engine.go#L299)
- [x] Alternatively, have a way to limit the concurrency of each build.

### Echo/time example

1. Build system loads dependency graph (fast-path extraction):

        echo -> time
        time
2. Builds time, extracting schema to `time/_ftl/schema.pb`
3. Build tool loads the schema.
4. Start building echo
5. Code-gens Kotlin stubs for time based on dependency graph
6. Build Kotlin

### Unit tests/CI

```
ftl build          # Just works
go test ./...     # Just works
```

### Integration tests/CI

```
ftl serve --background --recreate
ftl deploy  # Waits for modules to deploy
go test -tags integration ./...
ftl serve --stop
```

### Interactive development

```
ftl dev
# Profit
```

### Non-interactive development

```
ftl build
# Profit
```
